spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://localhost:3306/department
    username: root
    password: Mysql@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
custom:
  message: Hello, Department Service Updated
